
#

title:            "P2P Markets"
description:      "Discussion of the peer to peer lending markets and investment approaches"
disqus_shortname: p2pmarkets
reading_time:     false
words_per_minute: 200

logo:             /images/logo.png
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://mb389.github.io/port

logo:             images/peer-to-peer-icon.png
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
 #url: ''


menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Favorites'
    url: '/#'
    submenu:
      - title: 'highlighter'
        url: '/port/code-highlighting-post/'
      - title: 'intro'
        url: '/port/readability-post/'

# Owner/author information
owner:
  name:           Michael Bushoy
  site:           https://mb389.github.io
  avatar:         images/linkedinpic.jpg
  bio:            "I'm Mike and I’m a 30-year-old ex-Wall Street risk manager living in Brooklyn, NY. I’m a CFA charterholder and active stock & option investor with a passion for all things markets & investing."
  email:          mb389@outlook.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: mb389
  facebook: michael.bushoy
  github: mb389
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +AronBordin
  google_plus:    +mbushoy

social:
  - title: "github"
    url: "https://github.com/mb389"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/michael-bushoy-cfa-60a9896"
  - title: "youtube"
    url: ""
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
